### ISSUE TITLE
Support for Illumina reads?

### ISSUE THREAD

**Issue by tseemann** [mbhall88/lrge#5]
Would be good to support Illumina reads too.

Probably not your overlap method, but standard "number of unique 24-mers above frequency 3" for example.

And auto-detect the data platform too.

**Comment by mbhall88** [comment]
Probably not going to support short reads but I’d be open to adding some documentation suggesting what people can do to estimate genome size from illumina. I already have a section that discusses alternatives and these (mash and genomescope2) would probably fit the bill?
